on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pytest
      - name: Pylint
        run: pylint src
      - name: Pytest
        run: pytest
      - name: Build
        run: |
          pip install wheel
          make build
          make install
          which genshin-account-switcher
